### ISSUE TITLE
Fatal error: Uncaught Exception: The factory is not contains configuration for 'JSONReport'

### ISSUE THREAD

**Issue by korenevskiy** [KashifHK123/AI-Bolit#1]
Fatal error: Uncaught Exception: The factory is not contains configuration for 'JSONReport'. in /home/e/exoffice/art-rf.ru/public_html/ai-bolit.php:11828 Stack trace: #0 /home/e/exoffice/art-rf.ru/public_html/ai-bolit.php(2064): Factory->create('JSONReport', Array) #1 /home/e/exoffice/art-rf.ru/public_html/ai-bolit.php(4342): {closure}() #2 {main} thrown in /home/e/exoffice/art-rf.ru/public_html/ai-bolit.php on line 11828

Тоже самое в 

Fatal error: Uncaught Exception: The factory is not contains configuration for 'JSONReport'. in /home/e/exoffice/art-rf.ru/public_html/ai-bolit-hoster.php:11828 Stack trace: #0 /home/e/exoffice/art-rf.ru/public_html/ai-bolit-hoster.php(2064): Factory->create('JSONReport', Array) #1 /home/e/exoffice/art-rf.ru/public_html/ai-bolit-hoster.php(4342): {closure}() #2 {main} thrown in /home/e/exoffice/art-rf.ru/public_html/ai-bolit-hoster.php on line 11828
.
На сайте в ВК коментариях все пишут об этой проблеме.

**Comment by KashifHK123** [comment]
please install php-json library.
